import turtle
avery = turtle.Pen()
kate = turtle.Pen()
mich = turtle.Pen()
avery.forward(50)
avery.right(90)
avery.forward(20)
kate.left(180)
kate.forward(80)
kate.left(90)
kate.forward(80)
kate.left(90)
kate.forward(80)
kate.left(90)
kate.forward(80)
